//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.04 at 01:27:00 PM UTC 
//


package yahoo.jp.itemsearch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the yahoo.jp.itemsearch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: yahoo.jp.itemsearch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResultSet }
     * 
     */
    public ResultSet createResultSet() {
        return new ResultSet();
    }

    /**
     * Create an instance of {@link ResultSet.Result }
     * 
     */
    public ResultSet.Result createResultSetResult() {
        return new ResultSet.Result();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit }
     * 
     */
    public ResultSet.Result.Hit createResultSetResultHit() {
        return new ResultSet.Result.Hit();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Store }
     * 
     */
    public ResultSet.Result.Hit.Store createResultSetResultHitStore() {
        return new ResultSet.Result.Hit.Store();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Store.Payment }
     * 
     */
    public ResultSet.Result.Hit.Store.Payment createResultSetResultHitStorePayment() {
        return new ResultSet.Result.Hit.Store.Payment();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Brands }
     * 
     */
    public ResultSet.Result.Hit.Brands createResultSetResultHitBrands() {
        return new ResultSet.Result.Hit.Brands();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Brands.Path }
     * 
     */
    public ResultSet.Result.Hit.Brands.Path createResultSetResultHitBrandsPath() {
        return new ResultSet.Result.Hit.Brands.Path();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.CategoryIdPath }
     * 
     */
    public ResultSet.Result.Hit.CategoryIdPath createResultSetResultHitCategoryIdPath() {
        return new ResultSet.Result.Hit.CategoryIdPath();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules }
     * 
     */
    public ResultSet.Result.Modules createResultSetResultModules() {
        return new ResultSet.Result.Modules();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.Subcategories }
     * 
     */
    public ResultSet.Result.Modules.Subcategories createResultSetResultModulesSubcategories() {
        return new ResultSet.Result.Modules.Subcategories();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.Subcategories.Children }
     * 
     */
    public ResultSet.Result.Modules.Subcategories.Children createResultSetResultModulesSubcategoriesChildren() {
        return new ResultSet.Result.Modules.Subcategories.Children();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.Subcategories.Path }
     * 
     */
    public ResultSet.Result.Modules.Subcategories.Path createResultSetResultModulesSubcategoriesPath() {
        return new ResultSet.Result.Modules.Subcategories.Path();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.PriceRanges }
     * 
     */
    public ResultSet.Result.Modules.PriceRanges createResultSetResultModulesPriceRanges() {
        return new ResultSet.Result.Modules.PriceRanges();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Request }
     * 
     */
    public ResultSet.Result.Request createResultSetResultRequest() {
        return new ResultSet.Result.Request();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Image }
     * 
     */
    public ResultSet.Result.Hit.Image createResultSetResultHitImage() {
        return new ResultSet.Result.Hit.Image();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Price }
     * 
     */
    public ResultSet.Result.Hit.Price createResultSetResultHitPrice() {
        return new ResultSet.Result.Hit.Price();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.PriceLabel }
     * 
     */
    public ResultSet.Result.Hit.PriceLabel createResultSetResultHitPriceLabel() {
        return new ResultSet.Result.Hit.PriceLabel();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Point }
     * 
     */
    public ResultSet.Result.Hit.Point createResultSetResultHitPoint() {
        return new ResultSet.Result.Hit.Point();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Shipping }
     * 
     */
    public ResultSet.Result.Hit.Shipping createResultSetResultHitShipping() {
        return new ResultSet.Result.Hit.Shipping();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Store.Ratings }
     * 
     */
    public ResultSet.Result.Hit.Store.Ratings createResultSetResultHitStoreRatings() {
        return new ResultSet.Result.Hit.Store.Ratings();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Store.Image }
     * 
     */
    public ResultSet.Result.Hit.Store.Image createResultSetResultHitStoreImage() {
        return new ResultSet.Result.Hit.Store.Image();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Store.Payment.Method }
     * 
     */
    public ResultSet.Result.Hit.Store.Payment.Method createResultSetResultHitStorePaymentMethod() {
        return new ResultSet.Result.Hit.Store.Payment.Method();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.Brands.Path.Brand }
     * 
     */
    public ResultSet.Result.Hit.Brands.Path.Brand createResultSetResultHitBrandsPathBrand() {
        return new ResultSet.Result.Hit.Brands.Path.Brand();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Hit.CategoryIdPath.Category }
     * 
     */
    public ResultSet.Result.Hit.CategoryIdPath.Category createResultSetResultHitCategoryIdPathCategory() {
        return new ResultSet.Result.Hit.CategoryIdPath.Category();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.Subcategories.Children.Child }
     * 
     */
    public ResultSet.Result.Modules.Subcategories.Children.Child createResultSetResultModulesSubcategoriesChildrenChild() {
        return new ResultSet.Result.Modules.Subcategories.Children.Child();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.Subcategories.Path.Category }
     * 
     */
    public ResultSet.Result.Modules.Subcategories.Path.Category createResultSetResultModulesSubcategoriesPathCategory() {
        return new ResultSet.Result.Modules.Subcategories.Path.Category();
    }

    /**
     * Create an instance of {@link ResultSet.Result.Modules.PriceRanges.Range }
     * 
     */
    public ResultSet.Result.Modules.PriceRanges.Range createResultSetResultModulesPriceRangesRange() {
        return new ResultSet.Result.Modules.PriceRanges.Range();
    }

}
